---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio
  labels:
    app.kubernetes.io/instance: hawtio
    app.kubernetes.io/name: hawtio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: hawtio
      app.kubernetes.io/name: hawtio
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hawtio
        app.kubernetes.io/name: hawtio
    spec:
      enableServiceLinks: false
      containers:
      - image: ueisele/hawtio:2.14.5
        imagePullPolicy: Always
        name: envoy
        ports:
        - containerPort: 8081
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hawtio
  labels:
    app.kubernetes.io/instance: hawtio
    app.kubernetes.io/name: hawtio
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: hawtio
    app.kubernetes.io/name: hawtio
